---
- name: Setup WireGuard
  hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Include WireGuard role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."
