---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-wg-ubuntu2004
    box: alvistack/ubuntu-20.04
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
    groups:
      - vpn
      - ubuntu
  - name: test-wg-debian12
    box: alvistack/debian-12
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
    groups:
      - vpn
      - debian
  - name: test-wg-ubuntu2204
    box: alvistack/ubuntu-22.04
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
    groups:
      - vpn
      - ubuntu

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-wg-ubuntu2004:
        wireguard_address: "10.10.10.10/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.10"
      test-wg-debian12:
        wireguard_address: "10.10.10.20/24"
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: ""
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-ubuntu2204:
        wireguard_address: "10.10.10.30/24"
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: ""

scenario:
  name: single-server
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
