---
# Copyright (C) 2023-2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Verify setup
  hosts: all
  tasks:
    - name: Count WireGuard interfaces
      ansible.builtin.shell: |
        set -o errexit
        set -o pipefail
        set -o nounset
        wg | grep "peer: " | wc -l
        exit 0
      args:
        executable: "/bin/bash"
      register: wireguard__interfaces_count
      changed_when: false

    - name: Print WireGuard interface count
      ansible.builtin.debug:
        var: wireguard__interfaces_count.stdout

    - name: Set expected WireGuard peer count
      ansible.builtin.set_fact:
        wireguard__expected_peers: 0

    - name: Count expected WireGuard peers
      ansible.builtin.set_fact:
        wireguard__expected_peers: "{{ wireguard__expected_peers | int + 1 }}"
      loop: "{{ groups['vpn'] }}"
      when:
        - item != inventory_hostname
        - not (wireguard_as_spoke | default(false)) or not (hostvars[item].wireguard_as_spoke | default(false))
        - >-
          (hostvars[item].wireguard_endpoint is defined and
          hostvars[item].wireguard_endpoint != "") or
          (wireguard_endpoint is defined and wireguard_endpoint != "")

    - name: Print expected WireGuard peer count
      ansible.builtin.debug:
        var: wireguard__expected_peers

    - name: WireGuard peer count should match expected topology
      ansible.builtin.assert:
        that:
          - "wireguard__expected_peers | int == wireguard__interfaces_count.stdout | int"
