# Copyright (C) 2020 Roman Danko
# Copyright (C) 2023 Timmerman Jens 
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (CentOS 9) Install EPEL & ELRepo repository
  ansible.builtin.yum:
    name:
      - epel-release

- name: (CentOS 9) Install WireGuard packages
  ansible.builtin.yum:
    name:
      - "wireguard-tools"
    state: present

- name: (CentOS 9) Ensure WireGuard DKMS package is removed
  ansible.builtin.yum:
    name:
      - "wireguard-dkms"
    state: absent
