---
# Copyright (C) 2022 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Rocky Linux) Install wireguard-tools package
  ansible.builtin.yum:
    name: wireguard-tools
    state: present

- name: Install Systemd-resolved package if DNS is set
  block: 
    - name: install Systemd-resolved 
      ansible.builtin.yum:
        name: systemd-resolved
        state: present
    - name: enable Systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: started
        enabled: true
  when: wireguard_dns is defined
