---
# Copyright (C) 2020-2025 Robert Wimmer
# Copyright (C) 2020-2025 Pierre Ozoux
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-wg-ubuntu2004
    box: alvistack/ubuntu-20.04
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
    groups:
      - vpn
      - ubuntu
  - name: test-wg-fedora39
    box: generic/fedora39
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
    groups:
      - vpn
      - fedora
  - name: test-wg-fedora40
    box: alvistack/fedora-40
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
    groups:
      - vpn
      - fedora
  - name: test-wg-arch
    box: archlinux/archlinux
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.40
    groups:
      - vpn
      - archlinux
  - name: test-wg-debian11
    box: generic/debian11
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.50
    groups:
      - vpn
      - debian
  - name: test-wg-debian12
    box: generic/debian12
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.60
    groups:
      - vpn
      - debian
  - name: test-wg-opensuse-leap-15-6
    box: opensuse/Leap-15.6.x86_64
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.70
    groups:
      - vpn
      - opensuse
  - name: test-wg-ubuntu2204
    box: alvistack/ubuntu-22.04
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.110
    groups:
      - vpn
      - ubuntu
  - name: test-wg-ubuntu2404
    box: alvistack/ubuntu-24.04
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.120
    groups:
      - vpn
      - ubuntu
  - name: test-wg-opensuse-leap-15-5
    box: opensuse/Leap-15.5.x86_64
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.130
    groups:
      - vpn
      - opensuse
  - name: test-wg-rocky9
    box: bento/rockylinux-9
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.140
    groups:
      - vpn
      - el9
  - name: test-wg-alma9
    box: almalinux/9
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.150
    groups:
      - vpn
      - el9
  - name: test-wg-oracle9
    box: generic/oracle9
    memory: 1536
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.160
    groups:
      - vpn
      - el9

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-wg-ubuntu2004:
        wireguard_address: "10.10.10.10/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.10"
      test-wg-fedora39:
        wireguard_address: "10.10.10.20/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.20"
        wireguard_interface_restart: true
      test-wg-fedora40:
        wireguard_address: "10.10.10.30/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.30"
        wireguard_interface_restart: true
      test-wg-arch:
        wireguard_address: "10.10.10.40/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.40"
        ansible_python_interpreter: "/usr/bin/python"
      test-wg-debian11:
        wireguard_address: "10.10.10.50/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.50"
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-debian12:
        wireguard_address: "10.10.10.60/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.60"
        wireguard_conf_backup: true
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-opensuse-leap-15-6:
        wireguard_address: "10.10.10.70/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.70"
        wireguard_conf_backup: true
        ansible_python_interpreter: "/usr/bin/python3.9"
      test-wg-ubuntu2204:
        wireguard_address: "10.10.10.110/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.110"
        wireguard_conf_backup: true
      test-wg-ubuntu2404:
        wireguard_address: "10.10.10.120/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.120"
      test-wg-opensuse-leap-15-5:
        wireguard_address: "10.10.10.130/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.130"
        ansible_python_interpreter: "/usr/bin/python3.9"
      test-wg-rocky9:
        wireguard_address: "10.10.10.140/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.140"
      test-wg-alma9:
        wireguard_address: "10.10.10.150/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.150"
      test-wg-oracle9:
        wireguard_address: "10.10.10.160/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "172.16.10.160"

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
