---
# Copyright (C) 2021-2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Prepare opensuse hosts
  hosts: opensuse
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Remove backports repositories
      ansible.builtin.raw: |
        zypper rr repo-backports-debug-update
        zypper rr repo-backports-update
      changed_when: false
      failed_when: false

- name: Prepare Archlinux hosts
  hosts: archlinux
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      failed_when: false

    - name: Updating pacman cache
      ansible.builtin.raw: pacman -Sy
      changed_when: false
      failed_when: false

    - name: Install Python
      ansible.builtin.raw: |
        pacman -S --noconfirm python
      args:
        executable: /bin/bash
      changed_when: false

- name: Prepare Proxmox hosts
  hosts: proxmox
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: (Proxmox) Delete /var/lib/apt/lists/lock
      ansible.builtin.file:
        name: /var/lib/apt/lists/lock
        state: absent

- name: Prepare Ubuntu hosts
  hosts: ubuntu
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Prepare Enterprise Linux 8 hosts (DKMS)
  hosts: el8dkms
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Install ELRepo mainline kernel
      ansible.builtin.raw: |
        rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
        dnf install -y https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
        dnf --enablerepo=elrepo-kernel install -y kernel-ml
      changed_when: false
      failed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:

- name: Prepare Almalinux 8 hosts
  hosts: almalinux8
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Install ELRepo mainline kernel
      ansible.builtin.raw: |
        dnf -y upgrade
      changed_when: false
      failed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:
