---
# Copyright (C) 2021-2024 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Prepare opensuse hosts
  hosts: opensuse
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Install Python 3.9
      ansible.builtin.raw: |
        zypper install --no-confirm --no-recommends python39
      changed_when: false
      failed_when: false

- name: Prepare Archlinux hosts
  hosts: archlinux
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Init pacman
      ansible.builtin.raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      failed_when: false

    - name: Updating pacman cache
      ansible.builtin.raw: pacman -Sy
      changed_when: false
      failed_when: false

    - name: Install Python
      ansible.builtin.raw: |
        pacman -S --noconfirm python
      args:
        executable: /bin/bash
      changed_when: false

- name: Prepare Ubuntu hosts
  hosts: ubuntu
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Prepare Enterprise Linux 8 hosts
  hosts: rocky8
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Install ELRepo mainline kernel
      ansible.builtin.raw: |
        dnf --assumeyes install python39
      changed_when: false
      failed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:

- name: Prepare Enterprise Linux 8 hosts (DKMS)
  hosts: el8dkms
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Install ELRepo mainline kernel
      ansible.builtin.raw: |
        dnf --assumeyes --enablerepo=elrepo-kernel install kernel-ml
        dnf --assumeyes install python39
      changed_when: false
      failed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:

- name: Prepare Almalinux 8 hosts
  hosts: almalinux8
  remote_user: vagrant
  become: true
  gather_facts: false
  tasks:
    - name: Install Python 3.9
      ansible.builtin.raw: |
        dnf --assumeyes upgrade
        dnf --assumeyes install python39
      changed_when: false
      failed_when: false

    - name: Reboot for kernel updates
      ansible.builtin.reboot:
