---
# Copyright (C) 2020 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- hosts: all
  remote_user: vagrant
  become: true
  gather_facts: true
  tasks:
    - name: Init pacman
      raw: |
        pacman-key --init
        pacman-key --populate archlinux
      changed_when: false
      ignore_errors: true
      when: ansible_distribution|lower == 'archlinux'

    - name: (Proxmox) Delete /var/lib/apt/lists/lock
      file:
        name: /var/lib/apt/lists/lock
        state: absent
      ignore_errors: true
      when: ansible_kernel.find("pve") != -1

    - name: Include WireGuard role
      include_role:
        name: githubixx.ansible_role_wireguard
