---
# Copyright (C) 2020-2022 Robert Wimmer
# Copyright (C) 2020 Pierre Ozoux
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt
    options:
      memory: 192
      cpus: 2

platforms:
  - name: test-wg-ubuntu2004
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.10
    groups:
      - vpn
      - ubuntu
  - name: test-wg-ubuntu1804
    box: generic/ubuntu1804
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.20
    groups:
      - vpn
      - ubuntu
  - name: test-wg-debian10
    box: generic/debian10
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.30
    groups:
      - vpn
      - debian
  - name: test-wg-fedora34
    box: generic/fedora34
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.40
    groups:
      - vpn
      - fedora
  - name: test-wg-centos7
    box: generic/centos7
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.50
    groups:
      - vpn
      - el7
  - name: test-wg-arch
    box: archlinux/archlinux
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.60
    groups:
      - vpn
      - archlinux
  - name: test-wg-debian11
    box: generic/debian11
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.70
    groups:
      - vpn
      - debian
  - name: test-wg-rocky8
    box: generic/rocky8
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.80
    groups:
      - vpn
      - el8
  - name: test-wg-alma8
    box: generic/alma8
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.90
    groups:
      - vpn
      - el8
  - name: test-wg-centos7-kernel-plus
    box: generic/centos7
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.100
    groups:
      - vpn
      - el7
  - name: test-wg-opensuse-leap-15-3
    box: opensuse/Leap-15.3.x86_64
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.110
    groups:
      - vpn
      - opensuse
  - name: test-wg-fedora35
    box: generic/fedora35
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.120
    groups:
      - vpn
      - fedora
  - name: test-wg-rocky8-dkms
    box: generic/rocky8
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.130
    groups:
      - vpn
      - el8
      - el8dkms
  - name: test-wg-ubuntu2204
    box: alvistack/ubuntu-22.04
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.10.140
    groups:
      - vpn
      - ubuntu


provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      test-wg-ubuntu2004:
        wireguard_address: "10.10.10.10/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.10"
      test-wg-ubuntu1804:
        wireguard_address: "10.10.10.20/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.20"
      test-wg-debian10:
        wireguard_address: "10.10.10.30/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.30"
        ansible_python_interpreter: "/usr/bin/python"
      test-wg-fedora34:
        wireguard_address: "10.10.10.40/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.40"
        wireguard_interface_restart: true
      test-wg-centos7:
        wireguard_address: "10.10.10.50/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.50"
        wireguard_interface_restart: true
      test-wg-arch:
        wireguard_address: "10.10.10.60/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.60"
        ansible_python_interpreter: "/usr/bin/python"
      test-wg-debian11:
        wireguard_address: "10.10.10.70/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.70"
        ansible_python_interpreter: "/usr/bin/python3"
      test-wg-rocky8:
        wireguard_address: "10.10.10.80/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.80"
      test-wg-alma8:
        wireguard_address: "10.10.10.90/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.90"
      test-wg-centos7-kernel-plus:
        wireguard_address: "10.10.10.100/24"
        wireguard_port: 51821
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.100"
        wireguard_centos7_installation_method: "kernel-plus"
      test-wg-opensuse-leap-15-3:
        wireguard_address: "10.10.10.110/24"
        wireguard_port: 51822
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.110"
      test-wg-fedora35:
        wireguard_address: "10.10.10.120/24"
        wireguard_port: 51823
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.120"
      test-wg-rocky8-dkms:
        wireguard_address: "10.10.10.130/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.130"
        wireguard_rockylinux8_installation_method: "dkms"
      test-wg-ubuntu2204:
        wireguard_address: "10.10.10.140/24"
        wireguard_port: 51820
        wireguard_persistent_keepalive: "30"
        wireguard_endpoint: "192.168.10.140"

scenario:
  name: kvm
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
